### ISSUE TITLE
Allow access to setter mutations

### ISSUE THREAD

**Issue by bodograumann** [gertqin/vuex-class-modules#11]
When using the `generateMutationSetters` option, for each state property a mutation is generated, that sets the property.

Those setter mutations are only available inside of actions, not when using the module instance directly.

Do you think we should allow access from the outside? Or would you say that it is a much better practice to only do changes in the actions?

**Comment by gertqin** [comment]
So you want to do something like:

```ts
@Module({ generateMutationSetters: true })
class MyModule extends VuexModule {
  foo = "bar";
}
const myModule = new MyModule({ store, name: "myModule" });
myModule.foo = "baz";
```
?

It would not be hard to implement, but I'm not sure whether it is against the design principles of vuex (flux) or not. Do you think it would be beneficial to allow?

**Comment by bodograumann** [comment]
Yes this is what I mean.

I‘m not completely sure this follows the flux principles, but there are two reasons which let me lean towards yes:

- It is not the default setting, you have to enable `generateMutationSetters`.
- Even though the syntax is different, it simply commits a mutation, which is perfectly fine in flux as I understand it.

**Comment by gertqin** [comment]
Alright, I'll implement this. Although I think I'll keep it as an undocumented feature, as I'm still not sure whether this should be encouraged or not.
