### ISSUE TITLE
module inheritance

### ISSUE THREAD

**Issue by danieleades** [gertqin/vuex-class-modules#13]
is it possible to use inheritance to reuse common logic between modules using this package?

**Comment by gertqin** [comment]
Hmm, I haven't tried it, but I think the following should work (not tested)

```ts
class BaseModule extends VuexModule {
  someHelperFunction(a: number) {
    // ...
  }
}

@Module
class Module1 extends BaseModule {
  // can call this.someHelperFunction
}

@Module
class Module2 extends BaseModule {
  // can call this.someHelperFunction
}
```

But I dont think you can use the ```@Module``` decorator on the BaseModule.

Is this what you are looking for? Feel free to try it out, and if it doesn't work, let me know.

**Comment by gertqin** [comment]
Closing for now, feel free to reopen if you find some problems with inheritance.

**Comment by jo0ger** [comment]
@gertqin hi
Getters in the `BaseModule` do not work

``` js
class BaseModule extends VuexModule {
  get fullName () {/ ** /}
}

@Module
class ChildModule extends BaseModule {}
```
