### ISSUE TITLE
vue-router lazy loading broken

### ISSUE THREAD

**Issue by danieleades** [gertqin/vuex-class-modules#14]
I'm having trouble using both vuex-class-modules and vue-router lazy loading at the same time.

For reference- here is a commit of the project showing the issue-
https://github.com/danieleades/lazy-load-issue

- I have a page called 'transactions' which is lazily loaded in `router.ts`
```lang=ts
    {
      path: '/transactions',
      name: 'transactions',
      component: () => import(/* webpackChunkName: "transactions" */ './views/Transactions.vue'),
    },
```
- This route depends on a vuex module which is instantiated and registered in @/store/transactions.ts
``` lang=ts
const transactionsModule = new TransactionsModule({ store, name: 'transactions' });

export { transactionsModule };
```

```lang=ts
import { Component, Vue } from 'vue-property-decorator';
import { transactionsModule } from '@/store/transactions';

@Component
export default class TransactionsTable extends Vue {
get transactions() {
    return transactionsModule.transactions;
}
}
```
- localhost:XXXX/transactions never loads
- page loads normally if remove the dependency on the module, or remove the lazy loading from the router.

any ideas? This library is amazing, please don't make me go back to static, stringly-typed modules!

**Comment by danieleades** [comment]
If i move the dynamic module registration to the same file that i define the vuex store root in, it works perfectly. Of course then I no longer have lazy initialisation of the module.

**Comment by danieleades** [comment]
This works perfectly in production builds. I don't think this is anything to do with this package- more likely it's related to the default webpack configuration of the vue-cli service.

vuejs/vue-cli#3903

**Comment by gertqin** [comment]
Sorry for the late response, but I'm glad you figured it out. :)
