### ISSUE TITLE
$watch not working with state changes

### ISSUE THREAD

**Issue by frankshaka** [gertqin/vuex-class-modules#15]
This minimum example does not work as expected:

```typescript
import Vue from 'vue'
import Vuex from 'vuex'
import { VuexModule, Module, Mutation } from 'vuex-class-modules'

Vue.use(Vuex)

@Module
class Foo extends VuexModule {
    value: string = 'abc'
    @Mutation setValue(value: string) { this.value = value }
}

const store = new Vuex.Store({})
const foo = new Foo({ store, name: 'foo' })

foo.$watch(
    f => f.value,
    (value) => { console.log(value) }  /// watch state changes and output the new value
)

foo.setBar('xyz')
```

**Expected behavior:**

Output with `xyz`.

**Actual behavior:**

Output with `undefined`.

I reviewed the code and found the cause may be that `$watch` does not get namespaced state.

In `module-factory.ts`:

```typescript
    accessorModule.$watch = (
      fn: (arg: VuexModule) => any,
      callback: (newValue: any, oldValue: any) => void,
      options?: WatchOptions
    ) => {
      store.watch(
        (state: any, getters: any) => fn(this.buildThisProxy({ state, getters, useNamespaceKey: true })),
        callback,
        options
      );
    };
```

When calling `this.buildThisProxy()`, it should pass in `state: state[name]` instead.

Should I open a pull request for this?

**Comment by gertqin** [comment]
I think you are right! Thanks for finding it.

I can see the current test only tests for store getters and not state, so that's why this simple bug has gone unoticed (I haven't used the $watch api myself).

Feel free to open a pull request (and add a test case) if you want :)
