### ISSUE TITLE
Memoization technique with vuex-class-modules

### ISSUE THREAD

**Issue by jacek-jablonski** [gertqin/vuex-class-modules#18]
Hi,
thanks for this awsome library. I would like to use it with memoizee to get some TTL caching. I am trying to use it this way:
```
import memoize from "memoizee"
import { VuexModule, Module, Mutation, Action } from "vuex-class-modules"
import { Backend } from "@/store/modules/backends/models"
import { BackendsAPI } from "./api"
import store from "@/store"

@Module
class BackendsModule extends VuexModule {
  private _backends: Array<Backend> = []

  private _getBackendsMemoized = memoize(BackendsAPI.getBackends)

  public get backends() {
    return this._backends
  }

  @Mutation
  private setBackends(backends: Array<Backend>) {
    this._backends = backends
  }

  @Action
  public async fetchBackends() {
    const backends = await this._getBackendsMemoized()
    this.setBackends(backends)
  }
}
```
However, I get an error saying: ```TypeError: this._getBackendsMemoized is not a function```. Any ideas how can I use memoization in a smart way with vuex-class-modules?

**Comment by jo0ger** [comment]
@jacek-jablonski  try this

``` js
import memoize from "memoizee"
import { VuexModule, Module, Mutation, Action } from "vuex-class-modules"
import { Backend } from "@/store/modules/backends/models"
import { BackendsAPI } from "./api"
import store from "@/store"

const getBackendsMemoized = memoize(BackendsAPI.getBackends)

@Module
class BackendsModule extends VuexModule {
  private _backends: Array<Backend> = []

  public get backends() {
    return this._backends
  }

  @Mutation
  private setBackends(backends: Array<Backend>) {
    this._backends = backends
  }

  @Action
  public async fetchBackends() {
    const backends = await getBackendsMemoized()
    this.setBackends(backends)
  }
}
```

**Comment by jacek-jablonski** [comment]
@jo0ger thanks for example. I am aware I can throw memoize out of class. But is it possible to have memoize inside VuexModule?

**Comment by bodograumann** [comment]
In principal something like your original idea should work.
I have written my own buffering library, which I can use like
```typescript
@Module
class MyModule extends VuexModule {
    buffer: Buffer = new Buffer();

    @Action
    async fetchBackends() {
        return this.buffer.getItem();
    }
}
```

Things you could try:
- use `memoize(BackendsApi.getBackends.bind(BackendsApi))` or `memoize(() => BackendsApi.getBackends())`
- do not define `_backends` as `private`
- do not use an underscore at the beginning `_backends`

**Comment by jacek-jablonski** [comment]
Thanks for response:
> do not define _backends as private

Is it general advice? Or only applicable to this situation? I would like to have private properties and public getters.

**Comment by bodograumann** [comment]
No, in general it’s fine I think. This was only a shot in the dark.

I looked at the vuex-class-modules code and found the problem.
You are defining a property, which is also a function. Because its a function, it is not captured in the vuex state.
https://github.com/gertqin/vuex-class-modules/blob/bc353023e2fa21a46d3a9f656dc03a73442dc96c/src/module-factory.ts#L71-L77
But because it is not a real method of the class, it is not captured as unannotated method (aka local functions, aka helper function) either:
https://github.com/gertqin/vuex-class-modules/blob/bc353023e2fa21a46d3a9f656dc03a73442dc96c/src/module-factory.ts#L95-L104

So I guess its a bug. ;-)

**Comment by gertqin** [comment]
@bodograumann Good catch!

Now the question is - should it be a state value or a private helper function? Do you guys have any input?

**Comment by bodograumann** [comment]
In this case, having it as a private helper function would probably be sufficient. Still I think as a general approach it should be regarded as a proper state value.
Even if it doesn’t change, the overhead is not that big and in other scenarios we might actually want reactivity.
