### ISSUE TITLE
Simplify throttled vuex actions

### ISSUE THREAD

**Issue by jacek-jablonski** [gertqin/vuex-class-modules#19]
Hi,
I would like to throttle some Vuex actions, that shouldn't be performed more than once per 3 minutes. I am using lodash's throttle function like this:
```typescript
@Module
class AccountsModule extends VuexModule {
  private accounts = new Array<Account>()

  @Mutation
  private setAccounts(accounts: Array<Account>) {
    this.accounts = accounts
  }

  @Action
  public async fetchAccounts() {
    this.fetchThrottled()
  }
  
  fetchThrottled = _.throttle(performFetchAccounts, 3 * 60 * 1000, { trailing: false })

  performFetchAccounts() {
    AccountsAPI.getAccounts().then(accounts => this.setAccounts(accounts))
  }
}
```
Is there any way to simplify this call chain, so don't have to define 3 different functions for one throttled action or vuex-class-modules' internals forbids other way?

**Comment by bodograumann** [comment]
I agree that in principle something like this should be doable in a single line.

For a similar problem I tried implementing my own decorator based solutions. I tried several approaches, but in the end couldn’t get it to work.

**Comment by gertqin** [comment]
I haven't investigated whether it would be possible to have 

```ts
@Module
class AccountsModule extends VuexModule {
  private accounts = new Array<Account>()

  @Mutation
  private setAccounts(accounts: Array<Account>) {
    this.accounts = accounts
  }

  @Action fetchAccounts = _.throttle(performFetchAccounts, 3 * 60 * 1000, { trailing: false })
 
  performFetchAccounts() {
    AccountsAPI.getAccounts().then(accounts => this.setAccounts(accounts))
  }
}
```

but, would you prefer this syntax?

Unfortunately I'm quite busy at the moment, so I don't think I'll look into this for a while, but if you are up for it, feel free to open a pull request :)

**Comment by bodograumann** [comment]
Closing as stale. Feel free to reopen or open a new issue if you are still having problems with the suggested solution.
