### ISSUE TITLE
Nuxt problem

### ISSUE THREAD

**Issue by achimdan** [gertqin/vuex-class-modules#21]
I'm getting this error in nuxt 
[nuxt] store/index.ts should export a method that returns a vuex instance.
How can i fix it?

**Comment by gertqin** [comment]
I'm sorry but I haven't used Nuxt, so I don't know what their requirements to the store is. You'll have to investigate the problem yourself.

If you find a problem in vuex-class-modules when used with Nuxt feel free to open a new issue
