### ISSUE TITLE
Getters/function with parameters

### ISSUE THREAD

**Issue by IrynaBu** [gertqin/vuex-class-modules#27]
Hello!
Using standard vuex i was able to create getters function with params. How i can reach this using vuex-class-modules?

**Comment by bodograumann** [comment]
The only way I know of, in standard vuex or in vuex-class-modules, is by returning a function from the getter. For example:

```typescript
@Module
class UserModule extends VuexModule {
  get name() {
    return (id: number) => "Name of " + String(id);
  }
}
```

**Comment by IrynaBu** [comment]
Hi thanks! I will try this approach. Maybe you also can provide small piece of code how i can use this?

**Comment by bodograumann** [comment]
If you have a module instance, you can simply call the function like a normal method:
```typescript
export const userModule = new UserModule({ store, name: "user" });
console.log(userModule.name(42));
```

This works because the getter is used as `userModule.name` and returns a function, which you can then call.
