### ISSUE TITLE
Testing Vuex actions returns undefined

### ISSUE THREAD

**Issue by yasin-mesut** [gertqin/vuex-class-modules#28]
Hey there,

I couldn't find anything on SO so I'd like to ask here about. I recently moved from plain JS to TS and therefore started using `vuex-class-modules`. However, all of my tests using VueX that were working previously just stopped working with `vuex-class-modules`.

Is there anything special to take care about using `vuex-class-modules`?

I'm running tests on `Jest`.

----

After some more digging into `vuex-class-modules` I have to extend my question.

Using plain Vuex actions get triggered in my test and do what they are supposed to do. However, when I set up my test with `vuex-class-module`, by defining a `VuexModule` and putting in everything I need, my test still breaks. Is there by any chance some kind of 'how to' for working with `vuex-class-module`?

**Comment by bodograumann** [comment]
In principle there should no visible difference whether you use standard vuex methods or the vuex-class-modules interface. Can you please give more detailed information. Best would be some minimal reproduction repo. You should also definitely post more detailed error descriptions, apart from saying that your tests break. What are you testing for that is not working anymore?
Vuex-class-modules of course uses a specific naming scheme for its vuex modules, mutation, actions, etc. I would call that implementation details and so you shouldn't rely on it.

**Comment by yasin-mesut** [comment]
I'm sorry, you're totally right. I haven't been providing enough information though.

In `vuex-class-modules` we use classes and thus class members to define behaviors. That works pretty fine for me. However, when I try to test any component that's using the store, my test case simply fails. While I've been able to run successful tests using plain `Vuex` syntax, I can not get my `vuex-class-modules` tests running.

As an example, within my a test I have to reassign any action or mutation which is set in the store to a mock function - using `jest.fn()`.

As you can see in the below repo, test `HelloWorld` fails. That's just how it's supposed to be. However, test `HelloWorld2` fails as well, even though it's mocked and pointing to `jest.fn()`.

I actually don't know how that's going to get fixed properly. While being able to pass `jest.fn()` to an object member in vuex-style like so

```
actions: {
  count: jest.fn(),
}
```

this doesn't work for TypeScript classes which is why I'm assigning the mock function to a class member and just returning that.

Here's the example [repo](https://github.com/yasin-mesut/vuex-class-test).

**Comment by bodograumann** [comment]
I don‘t really see the need to use vuex or vuex-class-modules in those unit tests at all, because `helloWorldModule` is only a plain object with some state and methods to the component.
Basically you can mock out the whole thing. There are two ways to do that.
1. Use [jest.mock](https://jestjs.io/docs/en/es6-class-mocks) to mock the `/src/store` module.
2. Do not directly import from the store in your component, but use `@Provide` and `@Inject`. Then you can inject a mock of `helloWorldModule` directly into the tested component.

**Comment by yasin-mesut** [comment]
Thanks in advance. I'll just check that out. Also, the code provided was just a simple way to demonstrate the use case. The original code is used for user authentication and therefore I need to be able to check if the login function has been called or not.

**Comment by yasin-mesut** [comment]
First of all, thanks for your help so far. The above repo is updated and everything is working fine, except of one thing. Assuming an action returns a promise (or anything else), the return value is always undefined within the test, even though the code is working properly within the component itself. Any suggestions about that?

**Comment by bodograumann** [comment]
If the mocked module should return a value you need to define that with `mockResolvedValue`. See https://jestjs.io/docs/en/mock-functions.html#mocking-modules

**Comment by SantanderAuhAuh** [comment]
i have the same problem. Is there any solution?

**Comment by bodograumann** [comment]
This issue was solved afaik. What additional problem do you have?
