### ISSUE TITLE
Does it work with typescript module libs like vuex-class-modules?

### ISSUE THREAD

**Issue by pancake-boy** [gertqin/vuex-class-modules#31]
the modules are dynamically loaded, nothing is being saved.

```
import { VuexModule, Module, Mutation, Action } from 'vuex-class-modules';
import store from '@/store';
@Module
export default class QuoteModule extends VuexModule {
}
export const quoteModule = new QuoteModule({ store, name: 'quote' });

const vuexLocal = new VuexPersistence({
  storage: window.localStorage,
  modules: ['quote'],
});

export default new Vuex.Store({
  strict: true,
  /*
  Ideally if all your modules are dynamic
  then your store is registered initially
  as a completely empty object
  */
  plugins: [vuexLocal.plugin],
});
```

**Comment by bodograumann** [comment]
Not sure what you are asking @pancake-boy. Could you please elaborate?
Your code seems weird. You are importing a store from `@/store`, but then creating a new independent store and exporting that.

**Comment by pancake-boy** [comment]
thats to create an instance and register it into the store

**Comment by pancake-boy** [comment]
i'm gonna try switching to vuex-module-decorators and see how that goes

**Comment by bodograumann** [comment]
Feel free to reopen when you want to go into more detail.

**Comment by BonBonSlick** [comment]
@pancake-boy @bodograumann  hello, tell me pelase have you figured out how to persist state for this package with dynamic modules? Thanks.
