### ISSUE TITLE
Accessing Vue instance (_vm)

### ISSUE THREAD

**Issue by gutisalex** [gertqin/vuex-class-modules#33]
Trying to access vm:

`this._vm.$socket.client.emit('SomeEvent', data);`

Get error:

`Property '_vm' does not exist on type 'MyModule'.ts(2339)`

Any idea?

**Comment by bodograumann** [comment]
It is not possible afaik. Even in normal vuex it is only an implementation detail and should not be relied upon.
Also, accessing the vue instance goes against best-practices. For example you can have multiple vue instances using the same vuex store. Then the operation is not even well-defined.

As an alternative I would suggest explicitly giving the socket. You can either pass it in the constructor or later set it using a mutation.
