### ISSUE TITLE
Request for new feature - @Onload method decorator

### ISSUE THREAD

**Issue by LiamWiddop** [gertqin/vuex-class-modules#37]
I was looking to create a decorator to automatically call module methods on mounting a module, so I forked the repo [here](https://github.com/LiamJamesWiddop/vuex-class-modules) and added some lines to `src/module-factory` and `src/index.ts`. I also added `src/onload.ts`, which is basically an adaptation of `src/actions.ts`.

My changes basically add support for an `@Onload` method decorator and has worked in my tests. I was hoping that someone could review this as I believe it adds an interesting feature.

Thanks.

**Comment by bodograumann** [comment]
That sounds interesting. Could you actually create a pull request for it, please?

**Comment by LiamWiddop** [comment]
Sure, here you go: #38
