### ISSUE TITLE
Add vuex .watch API

### ISSUE THREAD

**Issue by bodograumann** [gertqin/vuex-class-modules#4]
As documented at https://vuex.vuejs.org/api/#watch, vuex allows to watch the state without having a vue component. E.g.

    store.watch(
        function(state, getters) {
            return getters.loggedIn;
        },
        loggedIn => {
            …
        }
    );

would execute a function every time the login state changes.

Afaics this is currently not possible when using vuex-class-modules. It would be nice to have a `watch` method where the callback is not called with `state` and `getters`, but with the vuex module. Maybe it should be called `$watch` to prevent naming conflicts.

(Note: The second parameter `getters` is not given with the latest `vuex` release v3.0.1. You’ll need the `master` branch for that.)

**Comment by gertqin** [comment]
You should still be able to use ```store.watch``` as the class modules are just wrappers of the normal vuex modules, you will however not get any typings. 

If that is what you want, can you then suggest a solution that would solve your problem? I haven't used ```store.watch``` in any of my projects.

**Comment by bodograumann** [comment]
The thing is that I don’t (want to) have access to the store at the point I’m using `watch`. Even if I had, I wouldn’t know what the namespace is called, where my getter lives. All that information is wonderfully captured by the vuex class module. Of course having typing information is also a goal.

I can try to create a pull request. My goal would be something like:

```typescript
/** MyModule.ts */
@Module
MyModule extends VuexModule {
    get myGetter() {
        …
    }
}

/** compose.ts */
myModule = new MyModule({ store, name: "anyModuleName" });

/** someOtherModule.ts */
myModule.$watch(
    (moduleRef: MyModule) => moduleRef.myGetter,
    newValue => {
        …
    }
);
```

**Comment by gertqin** [comment]
Ah, you want the watch api directly on the modules. I think that should be fairly easy to implement.

**Comment by bodograumann** [comment]
Yes. If you could do it, that would be fantastic. I would first have to get familiar with the code base.
