### ISSUE TITLE
Allow usage in node app without babel

### ISSUE THREAD

**Issue by ftes** [gertqin/vuex-class-modules#47]
## Observation
The sources are transpiled with a tsc `module` target of `es2015`.

## Problem
This makes them unusable in a node app with only a `typescript` setup (no `webpack` or `babel`):
```
./node_modules/vuex-class-modules/lib/index.js:1
export { Action } from "./actions";
^^^^^^

SyntaxError: Unexpected token 'export'
```

## Proposed solution
#46 Transpile to `commonjs` modules in addition to `es2015`.

**Comment by bodograumann** [comment]
Now that the PR is merged, are this complete, @ftes ?

**Comment by ftes** [comment]
Yes, thanks! Using it in our project already :).
