### ISSUE TITLE
Vuex 4 (Vue 3) support

### ISSUE THREAD

**Issue by micene09** [gertqin/vuex-class-modules#48]
Hi, first of all, thank you for the amazing job you have done with this library, it is saving the day in my frontend team in so many projects.

I know that this question could sounds hasty but, do you have any plan to support Vuex 4 and Vue 3 on the next releases?
Maybe I'm confused, but I didn't found any roadmap on this project.

**Comment by gertqin** [comment]
Yes I'm definitely planning to support Vuex 4 & Vue 3. We have not yet startet to migrate in my projects, but we will soon.

However I do believe this library should work out of the box for Vuex 4, as the api is the same as for Vuex 3. But if it doesn't I'll look into supporting Vuex 4 very soon.

**Comment by micene09** [comment]
Thank you bro! This is an amazing news!
