### ISSUE TITLE
Using class modules with inversifyjs

### ISSUE THREAD

**Issue by bodograumann** [gertqin/vuex-class-modules#6]
I'm having problems using the vuex class modules with InversifyJS.

From [the inversify docs](https://github.com/inversify/InversifyJS/blob/master/wiki/inheritance.md#what-can-i-do-when-my-base-class-is-provided-by-a-third-party-module) I took
```typescript
import { decorate, injectable } from "inversify";
decorate(injectable(), VuexModule);`
```

I’m not quite sure which order of the decorators is better, but `@Module` first seems sensible. I have implemented the feature #5 and added a test using InversifyJS in [bodograumann/vuex-class-modules#inversify](https://github.com/bodograumann/vuex-class-modules/tree/inversify).

```typescript
import { Module, VuexModule, RegisterOptions } from "../src";
import Vuex from "vuex";
import Vue from "vue";
import { Container, decorate, injectable, inject } from "inversify";
import "reflect-metadata";

Vue.use(Vuex);
const store = new Vuex.Store<any>({});

decorate(injectable(), VuexModule);

@injectable()
@Module
class MyModule extends VuexModule {
  constructor(
    @inject("Options") options: (className: string) => RegisterOptions
  ) {
    super(options);
  }

  foo = {
    text: "some text"
  };
  bar = 1;
}

const container = new Container();
container
  .bind<(className: string) => RegisterOptions>("Options")
  .toConstantValue((className: string) => ({ store, name: "myModule" }));

const myModule = container.resolve(MyModule);

test("instance of", () => {
  expect(myModule instanceof MyModule).toBe(true);
  expect(myModule instanceof VuexModule).toBe(true);
});
```
It fails with:

> The number of constructor arguments in the derived class accessor must be >= than the number of constructor arguments of its base class.

Is it possible that `@Module` is not retaining the `@inject` annotation? In that case I thought applying `@Module` after `@injectable()` would help, or at least git a different error, but nothing changes.

**Comment by gertqin** [comment]
I'm sorry, but as I don't use InversifyJS myself and am quite busy at the moment, I don't have the time to debug why it doesn't work with vuex-class-modules.

As for the order of decorators I guess you would want to have ```@Module``` first, then ```@injectable```, so that the parameters from ```injectable``` are passed to ```@Module```.

But I'm closing this issue, as it is out of scope for this project. Feel free to reopen, if you discover a specific bug in the implementation causing the issue. Or fork the project and adjust it to your needs.

**Comment by bodograumann** [comment]
Ok, I can completely understand that.
Hopefully in the future I will have some time to figure this out myself.
