### ISSUE TITLE
Is there a way to register the module without namespace?

### ISSUE THREAD

**Issue by dakuenjery** [gertqin/vuex-class-modules#66]
I like this library, but I cannot to register the module as a namespace: false.

I saw registerVuexModule() in module-factory.ts and the namespaced value is hardcoded, but maybe there is some workaround?

**Comment by bodograumann** [comment]
What you are trying to achieve by using non-namespaced modules?

**Comment by bodograumann** [comment]
I’ll close this now due to inactivity.
