### ISSUE TITLE
Vue Devtools not working

### ISSUE THREAD

**Issue by reynard80** [gertqin/vuex-class-modules#67]
I recently switched to class based Vuex modules with this package.
However, the Vuex tab of Vue Devtools doesn't seem to work anymore. It just shows the base state and no modules or mutations are recorded.

Is this a known issue or just my project?

![Knipsel](https://user-images.githubusercontent.com/32482953/125355785-b999d280-e365-11eb-9b9f-a77d8c9ca120.PNG)

**Comment by bodograumann** [comment]
I don’t think this can have anything to do with vuex-class-modules, as it is just a wrapper around vuex.
Could you please give the versions of vue, vuex and vue-devtools that you are using?
It could very well be that there is some incompatibility therein.
Beyond that, a minimal reproduction would be essential to even try to look at a possible issue.

**Comment by reynard80** [comment]
I understand. It would be strange if vuex-class-modules was the issue, but before I used vuex-module-decorators in the same project and this was working (but had other issues). 

We use Vue 2.6.14, Vuex 3.6.2 and Vue Devtools 5.3.4 in the project.

Only thing I can think of which might be a problem is that the modules are extended from abstract classes, like this: 

```
AbstractEntityStore extends VuexModule {
  ...
}

AbstractDataTableStore extends AbstractEntityStore {
  ...
}

UserEntityStore extends AbstractDataTableStore {
  ...
}

export default new UserEntityStore({ store, name: 'userEntity' })

```

As for reproduction, I will try to create a scaffolding project with just this construct and see if it works.

**Comment by bodograumann** [comment]
Inheritance can be problematic, if i remember correctly. Maybe check #20.

**Comment by reynard80** [comment]
It actually seems to be working now, also with inheritance. I actually had some settings wrong for Vue Devtools. 
Thanks for your reactions.
